apiVersion: apps/v1
kind: Deployment
metadata:
  name: uem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uem
  template:
    metadata:
      labels:
        app: uem
    spec:
      containers:
      - name: uem
        image: bjgomes/uem:main
        ports:
        - containerPort: 5000
          name: uem

---
apiVersion: v1
kind: Service
metadata:
  name: uem
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: uem

